---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    tty: true
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    override_command: false
    environment:
      container: docker
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        certbot_certs:
          - domains:
              - example1.com
              - example2.com
          - domains:
              - example3.com
        self_signed_certs_gen_dhparams: true
        self_signed_certs_key_size: 1024  # To make testing go faster, this should never happen in production.
        self_signed_certs_subject_country: US
        self_signed_certs_subject_city: San Francisco
        self_signed_certs_subject_org_name: Self Signed
        self_signed_certs_subject_org_unit: Self Signed Certificates Department

verifier:
  name: testinfra
  # options:
  #   vv: True
lint: |
  set -e
  yamllint .
  ansible-lint -x 204
  flake8 --max-line-length=120
