---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: xenial
    image: triplepoint/ubuntu-systemd-16.04
    privileged: true
    command: /bin/bash -c "exec /sbin/init --log-target=journal 3>&1"
  - name: bionic
    image: triplepoint/ubuntu-systemd-18.04
    privileged: true
    command: /bin/bash -c "exec /sbin/init --log-target=journal 3>&1"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        certbot_certs:
          - domains:
              - example1.com
              - example2.com
          - domains:
              - example3.com
        self_signed_certs_gen_dhparams: true
        self_signed_certs_key_size: 1024  # To make testing go faster, this should never happen in production.
        self_signed_certs_subject_country: US
        self_signed_certs_subject_city: San Francisco
        self_signed_certs_subject_org_name: Self Signed
        self_signed_certs_subject_org_unit: Self Signed Certificates Department

scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
