---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    role-file: molecule/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  # - name: ubuntu_14_04
  #   image: triplepoint/ubuntu-upstart-14.04
  #   command: /sbin/init
  - name: ubuntu_16_04
    image: triplepoint/ubuntu-systemd-16.04
    privileged: True
    command: /sbin/init
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        certbot_certs:
          - domains:
              - example1.com
              - example2.com
          - domains:
              - example3.com
        self_signed_certs_subject_country: US
        self_signed_certs_subject_city: San Francisco
        self_signed_certs_subject_org_name: Self Signed
        self_signed_certs_subject_org_unit: Self Signed Certificates Department

  config_options:
    ssh_connection:
      pipelining: True
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
